export const button = {
  auth: {
    active: { width: 400, height: 80, bgcolor: "#00a1e5", fontSize: 32 },
    disabled: { width: 400, height: 80, bgcolor: "#AEAEAE", fontSize: 32 },
  },
  round: {
    brownBig: {
      width: 279,
      height: 95,
      bgcolor: "#C4A267",
      fontSize: 36,
      borderRadius: 50,
      fontFamily: "Rasa",
      fontWeight: 700,
      textTransform: "none",
    },
    greenBig: {
      width: 279,
      height: 95,
      bgcolor: "#5DCE7C",
      fontSize: 48,
      borderRadius: 50,
      fontFamily: "Rasa",
      fontWeight: 700,
      textTransform: "none",
    },
    blackBig: {
      width: 279,
      height: 95,
      bgcolor: "#494357",
      fontSize: 36,
      borderRadius: 50,
      fontFamily: "Rasa",
      fontWeight: 700,
      textTransform: "none",
    },
    greenSmall: {
      width: 130,
      height: 45,
      bgcolor: "#5DCE7C",
      fontSize: 30,
      borderRadius: 50,
      fontFamily: "Rasa",
      fontWeight: 700,
      textTransform: "none",
    },
    blackSmall: {
      width: 130,
      height: 45,
      bgcolor: "#494357",
      fontSize: 30,
      borderRadius: 50,
      fontFamily: "Rasa",
      fontWeight: 700,
      textTransform: "none",
    },
    redSmall: {
      width: 130,
      height: 45,
      bgcolor: "#CE6A5D",
      fontSize: 30,
      borderRadius: 50,
      fontFamily: "Rasa",
      fontWeight: 700,
      textTransform: "none",
    },
    greenMediumAccept: {
      width: 192,
      height: 56,
      bgcolor: "#5DCE7C",
      fontSize: 39,
      borderRadius: 50,
      fontFamily: "Rasa",
      fontWeight: 700,
      textTransform: "none",
    },
    greenMedium: {
      width: 190,
      height: 55,
      bgcolor: "#5DCE7C",
      fontSize: 30,
      borderRadius: 50,
      fontFamily: "Rasa",
      fontWeight: 700,
      textTransform: "none",
    },
    redMedium: {
      width: 190,
      height: 55,
      bgcolor: "#CE6A5D",
      fontSize: 30,
      borderRadius: 50,
      fontFamily: "Rasa",
      fontWeight: 700,
      textTransform: "none",
      mr: 4,
    },
    redLong: {
      width: 300,
      height: 60,
      bgcolor: "#CE6A5D",
      fontSize: 30,
      borderRadius: 50,
      fontFamily: "Rasa",
      fontWeight: 700,
      textTransform: "none",
    },
    greenLong: {
      width: 300,
      height: 60,
      bgcolor: "#5DCE7C",
      fontSize: 30,
      borderRadius: 50,
      fontFamily: "Rasa",
      fontWeight: 700,
      textTransform: "none",
    },
  },
};
